version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts  # Official Jenkins LTS image
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"  # Expose Jenkins web interface on port 8080
      - "50000:50000"  # Expose the Jenkins agent port
    volumes:
      - jenkins_home:/var/jenkins_home  # Persist Jenkins data
    networks:
      - jenkins_network

volumes:
  jenkins_home:

networks:
  jenkins_network:
    driver: bridge
